
{'date': 'Sat Jul 14 2018 17:31:03.587 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 15
  m6n=http://images.tcdn.com.br/img/img_prod/419216/balao_de_decoracao_de_festa_aniversario_marshall_patrulha_canina_1872_3_20180312095941.jpg
           ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat Jul 14 2018 17:31:36.138 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 2
  http://images.tcdn.com.br/img/img_prod/419216/balao_de_decoracao_de_festa_aniversario_marshall_patrulha_canina_1872_3_20180312095941.jpg
       ^
SyntaxError: invalid syntax
'''},
{'date': 'Sun Jul 22 2018 11:19:43.621 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 27
  noite = Cena(img = NOITE)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Jul 22 2018 11:20:32.436 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 24
    class Tabuleiro:
  module <module> line 30
    self.fase1= Cena(img=FASE1, tit = "SIMETRICO 3 X 4", style = dict(left=200, top="100px", width=540, height="320px"))
  module _spy.vitollino.main line 696
    Cena.c(**kwargs)
  module _spy.vitollino.main line 739
    imagem, kwargs = (imagem, {}) if isinstance(imagem, str) \
KeyError: img
'''},
{'date': 'Sun Jul 22 2018 11:21:49.516 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 30
  self.fase1= Cena(img=FASE1, tit = "SIMETRICO 3 X 4", style = dict(left=200, top="100px", width=540, height="320px"))
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Jul 22 2018 11:23:54.906 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 47
    Tabuleiro ()
  module <module> line 28
    self.fase1= Cena(img=FASE1, tit = "SIMETRICO 3 X 4", style = dict(left=200, top="100px", width=540, height="320px"))
  module _spy.vitollino.main line 696
    Cena.c(**kwargs)
  module _spy.vitollino.main line 739
    imagem, kwargs = (imagem, {}) if isinstance(imagem, str) \
KeyError: img
'''},
{'date': 'Sun Jul 22 2018 11:36:13.49 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  self.noite = Cena(img = NOITE)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Jul 22 2018 11:36:39.985 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  self.noite = Cena(img = NOITE)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Jul 22 2018 11:37:20.336 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 35
  """ self.fase2= Cena(img=FASE2, tit = "SIMETRICO 3 X 4", style = dict(left=200, top="100px", width=540, height="320px"))
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sun Jul 22 2018 11:45:48.752 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 31
  self..fase1.qverde = Elemento(img=QVERDE,style = dict(left=200, top="100px", width=20, height="20px"))
        ^
SyntaxError: invalid syntax
'''},
{'date': 'Sun Jul 22 2018 11:48:26.692 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 61
    Tabuleiro()
  module <module> line 32
    self.fase1.qverde.entra (self.fase1)
  module _spy.vitollino.main line 453
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Elemento' object has no attribute 'nome'
'''},
{'date': 'Sun Jul 22 2018 12:20:27.488 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 25
  def cenario(cenario):
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Jul 22 2018 12:20:57.123 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 26
  noite = Cena(img = NOITE)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sun Jul 22 2018 12:24:20.650 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 29
    Tabuleiro ()
  module <module> line 26
    noite.vai()
NameError: name 'noite' is not defined
'''},
{'date': 'Sun Jul 22 2018 12:24:58.849 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 29
    Tabuleiro ()
  module <module> line 28
    fase1.entra (noite)
NameError: name 'fase1' is not defined
'''},
{'date': 'Sun Jul 22 2018 12:25:26.742 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 29
    Tabuleiro ()
  module <module> line 28
    self.fase1.entra (noite)
NameError: name 'noite' is not defined
'''},
{'date': 'Sun Jul 22 2018 12:33:28.281 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 31
    Tabuleiro ()
  module <module> line 26
    noite.vai()
NameError: name 'noite' is not defined
'''},
{'date': 'Sun Jul 22 2018 12:36:24.657 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 31
    Tabuleiro ()
  module <module> line 30
    self.qsimbolo.entra(self.fase1)
  module _spy.vitollino.main line 453
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Elemento' object has no attribute 'nome'
'''},
{'date': 'Sun Jul 22 2018 12:37:14.717 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 31
    Tabuleiro ()
  module <module> line 30
    self.qsimbolo.entra(self.fase1)
  module _spy.vitollino.main line 453
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Elemento' object has no attribute 'nome'
'''},
{'date': 'Sun Jul 22 2018 12:45:06.78 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 31
    Tabuleiro ()
  module <module> line 30
    self.qsimbolo.entra(self.fase1)
  module _spy.vitollino.main line 453
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Elemento' object has no attribute 'nome'
'''},