
{'date': 'Tue Jul 24 2018 16:42:17.937 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    STYLE["width"]=1100
NameError: name 'STYLE' is not defined
'''},
{'date': 'Tue Jul 24 2018 16:46:40.699 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    STYLE["width"]=1100
NameError: name 'STYLE' is not defined
'''},
{'date': 'Tue Jul 24 2018 14:32:31.391 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 120
    Tabuleiro()
  module <module> line 89
    self.tabuleiro[nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
NameError: name 'FUNDO_BRANCO' is not defined
'''},
{'date': 'Tue Jul 24 2018 15:41:03.843 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 80
  "self.casa0 = Elemento(QAZUL, tit='0_0', style=dict(width=TBX, height=TBY, left=220, top=120))
                                                                                                ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Wed Jul 25 2018 06:21:23.953 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 118
    Tabuleiro()
  module <module> line 53
    self.tabela_fase1 = tabelafase1 = Cena(img=FUNDO)
NameError: name 'FUNDO' is not defined
'''},
{'date': 'Wed Jul 25 2018 06:31:48.225 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  self.resposta_certa = {nome:pos.split("_") for nome,pos in zip(Pilha_Cartas,respostas.split(","))}
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 25 2018 13:03:48.899 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 31
    cliques = [ (3,verbos_altos),(2,verbos_medios),(1,verbos_fracos)]
NameError: name 'verbos_altos' is not defined
'''},
{'date': 'Wed Jul 25 2018 14:39:40.183 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 115
  def remove_clique_aqui(_):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 25 2018 14:39:53.521 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 115
  def remove_clique_aqui(_):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 25 2018 14:45:30.971 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 107
    nome = "{}_{}".format(linha, coluna)
NameError: name 'linha' is not defined
'''},
{'date': 'Wed Jul 25 2018 14:45:54.206 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 108
    self.tabuleiro[nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
NameError: name 'coluna' is not defined
'''},
{'date': 'Wed Jul 25 2018 14:48:18.68 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 99
    self.tabuleiro[nome].entra(tabelafase1)
AttributeError: 'Tabuleiro' object has no attribute 'tabuleiro'
'''},
{'date': 'Wed Jul 25 2018 14:48:33.858 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 123
    self.tabuleiro[nome].elt.onclick = recoloca_clique_aqui
AttributeError: 'Tabuleiro' object has no attribute 'tabuleiro'
'''},
{'date': 'Wed Jul 25 2018 14:53:46.806 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 91
  self.tabuleiro = {esquerda = {}, direita = {}}
                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jul 25 2018 14:55:11.495 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 97
    self.tabuleiro[esquerda[nome]] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
NameError: name 'esquerda' is not defined
'''},
{'date': 'Wed Jul 25 2018 14:55:34.974 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 97
    self.tabuleiro.esquerda[nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
AttributeError: 'dict' object has no attribute 'esquerda'
'''},
{'date': 'Wed Jul 25 2018 14:57:33.829 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 99
    self.tabuleiro[esquerda[nome]].entra(tabelafase1)
NameError: name 'esquerda' is not defined
'''},
{'date': 'Wed Jul 25 2018 14:58:32.437 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 108
    self.tabuleiro["direita"][nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
KeyError: direita
'''},
{'date': 'Wed Jul 25 2018 14:59:30.593 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 108
    self.tabuleiro["direita"][nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
KeyError: direita
'''},
{'date': 'Wed Jul 25 2018 15:00:14.393 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 108
    self.tabuleiro["direita"][nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
KeyError: direita
'''},
{'date': 'Wed Jul 25 2018 15:01:28.994 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 108
    self.tabuleiro["direita"][nome] = Elemento(FUNDO_BRANCO, tit=nome+"_", style=dict(
KeyError: direita
'''},
{'date': 'Wed Jul 25 2018 15:02:17.111 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Tabuleiro()
  module <module> line 123
    self.tabuleiro[nome].elt.onclick = recoloca_clique_aqui
KeyError: 3_2
'''},
{'date': 'Wed Jul 25 2018 15:04:33.105 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 121
  self.cliqueaqui.entra(self.tabelafase1)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 25 2018 15:11:33.761 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 132
    Tabuleiro()
  module <module> line 123
    for nome in tabuleiro["direita"]:
NameError: name 'tabuleiro' is not defined
'''},
{'date': 'Wed Jul 25 2018 15:12:52.421 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 134
    Tabuleiro()
  module <module> line 102
    self.tabuleiro["direita"][nome].elt.onclick = move_carta   
KeyError: 0_0
'''},
{'date': 'Wed Jul 25 2018 15:38:04.425 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 38
  if(casa.target.ocupado = False):
                          ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jul 25 2018 15:46:47.114 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  if((tabuleiro_target == "esquerda" && self.tabuleiro["direita"][casa_destino].ocupado == 1) 
                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jul 25 2018 15:47:19.576 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  if((tabuleiro_target == "esquerda" and self.tabuleiro["direita"][casa_destino].ocupado == 1) 
                                                                                                                                     ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jul 25 2018 15:47:47.104 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  if((tabuleiro_target == "esquerda" and self.tabuleiro["direita"][casa_destino].img.ocupado == 1) 
                                                                                                                                         ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jul 25 2018 15:59:00.882 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 132
    Tabuleiro()
  module <module> line 62
    Pilha_Cartas.append(QZUL)#lista das cartas
NameError: name 'QZUL' is not defined
'''},
{'date': 'Wed Jul 25 2018 16:00:16.181 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 109
    Tabuleiro()
  module <module> line 52
    a_carta_a_ser_empilhada.posicao_certa = self.resposta_certa[carta]
AttributeError: 'Tabuleiro' object has no attribute 'resposta_certa'
'''},
{'date': 'Wed Jul 25 2018 16:05:33.632 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 85
  """"      
            ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Wed Jul 25 2018 16:18:10.175 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  def move_carta(casa):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Jul 25 2018 16:22:53.903 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 14
  def remover_carta(_*):
                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jul 25 2018 16:33:25.811 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 92
    Tabuleiro()
  module <module> line 72
    Pilha_Cartas.top = "30px"
AttributeError: 'list' object has no attribute 'top'
'''},
{'date': 'Thu Jul 26 2018 10:51:43.367 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  pontos_altos =
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Sun Jul 29 2018 15:52:06.322 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 35
  carta_a_mover = self.lista_de_cartas.pop()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sun Jul 29 2018 15:52:15.286 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 35
  carta_a_mover = self.lista_de_cartas.pop()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sun Jul 29 2018 16:05:56.584 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 35
  carta_a_mover = self.lista_de_cartas.pop()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sun Jul 29 2018 16:06:30.837 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 35
  carta_a_mover = self.lista_de_cartas.pop()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sun Jul 29 2018 18:46:22.150 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 108
  def segunda_fase(self)
                         ^
SyntaxError: invalid syntax
'''},