
{'date': 'Thu Dec 05 2019 10:41:03.885 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  gameInicio():
               ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Dec 05 2019 10:41:56.31 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 21
    gameInicio()
  module <module> line 15
    gameInicio = Cena(CENAINICIO)
NameError: name 'CENAINICIO' is not defined
'''},
{'date': 'Thu Dec 05 2019 10:41:58.424 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 21
    gameInicio()
  module <module> line 15
    gameInicio = Cena(CENAINICIO)
NameError: name 'CENAINICIO' is not defined
'''},
{'date': 'Thu Dec 05 2019 10:42:00.993 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 21
    gameInicio()
  module <module> line 15
    gameInicio = Cena(CENAINICIO)
NameError: name 'CENAINICIO' is not defined
'''},
{'date': 'Thu Dec 05 2019 10:42:15.715 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 21
    gameInicio()
  module <module> line 18
    self.logotipo = Elemento(LOGO, x=370, y=30,w=650,h=400, cena=gameInicio)
NameError: name 'LOGO' is not defined
'''},
{'date': 'Thu Dec 05 2019 10:50:33.737 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  def toca(self, ev=0):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Thu Dec 05 2019 10:51:51.938 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 39
    gameInicio()
  module <module> line 19
    self.play = Elemento(PLAY, x=570, y=470,w=180,h=120, cena=gameInicio, vai = self.mostradia)
NameError: name 'PLAY' is not defined
'''},
{'date': 'Thu Dec 05 2019 13:00:49.699 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 68
    Basico()
  module <module> line 63
    self.doggie = Personagem(DOG, destino=self.cart, cena=cena)
AttributeError: 'Basico' object has no attribute 'cart'
'''},
{'date': 'Thu Dec 05 2019 13:16:36.933 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 19
  super().__init__(imagem, cena=cena, w=200, style=dict(backgroundColor="black",opacity=0.2) x=x, y=y)
                                                                                              ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Dec 05 2019 13:30:30.136 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    Basico()
  module <module> line 65
    self.casa = Predio(PRED, y=200, cena=cena)
TypeError: __init__() got an unexpected keyword argument 'cena'
'''},
{'date': 'Thu Dec 05 2019 13:35:11.805 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    Basico()
  module <module> line 65
    self.casa = Predio(PRED, x=350, y=180, cena=cena)
TypeError: __init__() got an unexpected keyword argument 'x'
'''},
{'date': 'Thu Dec 05 2019 11:52:14.99 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 80
    Basico()
  module <module> line 75
    self.casa = Predio(PRED, cena=cena, x=500, y =180)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:04:38.630 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    Basico()
  module <module> line 76
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:04:53.311 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    Basico()
  module <module> line 76
    self.casa = Predio(PRED, cena=Cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:05:12.288 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    Basico()
  module <module> line 76
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:06:15.148 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    Basico()
  module <module> line 76
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:07:48.628 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 80
    Basico()
  module <module> line 75
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:11:02.55 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 80
    Basico()
  module <module> line 75
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:11:46.667 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 80
    Basico()
  module <module> line 75
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:12:41.409 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 79
    Basico()
  module <module> line 74
    self.casa = Predio(PRED, cena=cena)
TypeError: __init__() takes 1 positional arguments but more were given
'''},
{'date': 'Thu Dec 05 2019 12:41:20.124 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    Basico()
  module <module> line 71
    self.casa.entra(self)
  module _spy.vitollino.main line 472
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Basico' object has no attribute 'nome'
'''},
{'date': 'Thu Dec 05 2019 12:44:11.182 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 77
    Basico()
  module <module> line 65
    self.casa.entra(Cena)
  module _spy.vitollino.main line 472
    self.scorer.update(valor=cena.nome, move=self.xy,
AttributeError: 'Cena' object has no attribute 'nome'
'''},
{'date': 'Thu Dec 05 2019 14:09:57.385 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    Basico()
  module <module> line 63
    self.cena = cena = Cena(CENA)
NameError: name 'CENA' is not defined
'''},
{'date': 'Thu Dec 05 2019 13:35:04.364 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 72
    Basico()
  module <module> line 61
    self.doggie = Personagem(DOG, destino=self.cesta, cena=cena) 
AttributeError: 'Basico' object has no attribute 'cesta'
'''},
{'date': 'Thu Dec 05 2019 13:36:12.379 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 72
    Basico()
  module <module> line 61
    self.doggie = Personagem(DOG, destino=self.cesta, cena=cena)
AttributeError: 'Basico' object has no attribute 'cesta'
'''},
{'date': 'Thu Dec 05 2019 13:36:16.569 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 72
    Basico()
  module <module> line 61
    self.doggie = Personagem(DOG, destino=self.cesta, cena=cena)
AttributeError: 'Basico' object has no attribute 'cesta'
'''},
{'date': 'Thu Dec 05 2019 13:52:33.479 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  def move(self, evento=None):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Thu Dec 05 2019 13:53:06.572 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  def move(self, evento=None):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Thu Dec 05 2019 13:53:35.743 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 94
    Basico()
  module <module> line 89
    self.doggie = Personagem3(BOY, destino=self.cesta, cena=cena)
  module <module> line 53
    self.vai = self.move
AttributeError: 'Personagem3' object has no attribute 'move'
'''},
{'date': 'Thu Dec 05 2019 13:54:49.912 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 94
    Basico()
  module <module> line 89
    self.menino = Personagem3(BOY, destino=self.cesta, cena=cena)
  module <module> line 53
    self.vai = self.move
AttributeError: 'Personagem3' object has no attribute 'move'
'''},
{'date': 'Thu Dec 05 2019 13:55:59.93 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 55
  def move(self, evento=None):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Thu Dec 05 2019 14:15:29.394 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 60
  def __init__(self, imagem, destino, cena, x=90, y=0)*2:
                                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Dec 10 2019 14:43:42.414 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 103
  self.cesta2 = Veiculo (CEST, destino= self.base0, cena= self,base1, x=200)
                                                                    ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Tue Dec 10 2019 14:44:45.864 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 103
  self.cesta2 = Veiculo(CEST, destino= self.base0, cena= self,base1, x=200)
                                                                   ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Tue Dec 10 2019 14:49:20.502 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 103
  self.cesta2 = Veiculo(CEST, destino= self.base0, cena= self,base1)
                                                                   ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Tue Dec 10 2019 16:24:55.86 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 119
    Basico()
  module <module> line 108
    self.doggie = Personagem(DOG, destino=self.cesta.fundo, cena=cena)
TypeError: __init__ missing 1 positional argument: 'texto'
'''},
{'date': 'Tue Dec 10 2019 16:28:22.852 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 116
    Basico()
  module <module> line 108
    self.doggie = Personagem(DOG, destino=self.cesta.fundo, cena=cena)
TypeError: __init__ missing 1 positional argument: 'texto'
'''},
{'date': 'Tue Dec 10 2019 16:36:56.247 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 70
  self.fundo = Elemento(img = CESTF,cena=self, x=10, y=10, w=100, h = )
                                                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 09:56:33.981 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 31
    class Personagem(Elemento, x, y): #dog
NameError: name 'x' is not defined
'''},
{'date': 'Wed Dec 11 2019 10:01:35.253 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 33
  super().__init__(imagem, cena=cena,  tit, x=x, y=y, w=80, h=h)
                                          ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Wed Dec 11 2019 10:01:50.670 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 110
  self.menina = Personagem(GIRL, destino=self.cesta.fundo, cena=cena, tit = "20kg" x=620, y=120, h=80)
                                                                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 10:54:38.652 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 171
  #Basico()
           ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Dec 11 2019 10:55:00.379 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 171
  #Basico()
           ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Dec 11 2019 10:55:02.137 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 171
  #Basico()
           ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Dec 11 2019 10:55:11.392 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 171
  #Basico()
           ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Dec 11 2019 11:15:05.439 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  Sw1 = !Sw1
         ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 11:27:49.162 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: <TypeError: bases[i].$dict is undefined>
'''},
{'date': 'Wed Dec 11 2019 11:40:03.495 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: <TypeError: bases[i].$dict is undefined>
'''},
{'date': 'Wed Dec 11 2019 11:55:34.140 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 175
    Basico()
  module <module> line 165
    self.cesta.outro, self.cesta2.outro = self.cesta2.outro, self.cesta.outro
AttributeError: 'Basico' object has no attribute 'cesta2'
'''},